version: '3.4'

services:  
  ecommerce-beymen:
      image: ecommerce-beymen
      build: 
        dockerfile: ECommerce.Api/Dockerfile
      ports:
        - "8080:80"
      depends_on:
        - ms-sql-server        
        - redis
      networks:
      - mynetwork

  ms-sql-server:
      container_name: ms-sql-server
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        SA_PASSWORD: "Password@12345"
        ACCEPT_EULA: "Y"
        MSSQL_PID: Express
      ports:
      - "1433:1433"
      networks:
      - mynetwork

  redis:
    container_name: redis
    image: redis
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db 
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
 mynetwork:
  driver: bridge
      
 
   
  